name: Assemble library

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Override tunnelVersion'
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build aar
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "Building with version ${{ github.event.inputs.version }}"
            ./gradlew tunnel:assembleRelease -PTUNNEL_VERSION=${{ github.event.inputs.version }}
          else
            echo "No version provided, using default from gradle.properties"
            ./gradlew tunnel:assembleRelease
          fi

      - name: Upload library
        uses: actions/upload-artifact@v6
        with:
          name: library
          path: tunnel/build/outputs/aar/*.aar
